from __future__ import annotations

from pathlib import Path

from github_interest_studio.planner import Recommendation


def _roadmap_for_item(item: Recommendation) -> str:
    title = item.project.title
    hours = item.project.estimated_hours
    chunk = max(hours // 4, 3)
    return "\n".join(
        [
            f"### {title}",
            "",
            f"- Score: `{item.score}`",
            f"- Difficulty: `{item.project.difficulty}`",
            f"- Estimated effort: `{hours}` hours",
            "",
            "1. Scope and architecture",
            f"   - Time box: {chunk}h",
            "2. Core implementation",
            f"   - Time box: {chunk * 2}h",
            "3. Tests and reliability",
            f"   - Time box: {chunk}h",
            "4. Demo, docs, and release",
            f"   - Time box: {chunk}h",
            "",
        ]
    )


def write_markdown_roadmap(path: str | Path, recommendations: list[Recommendation]) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    sections = [
        "# GitHub Project Roadmap",
        "",
        "This roadmap was generated by `github_interest_studio`.",
        "",
    ]
    for item in recommendations:
        sections.append(_roadmap_for_item(item))
    target.write_text("\n".join(sections).strip() + "\n", encoding="utf-8")
    return target
